name: Create Issue on New Repo

on:
  repository_dispatch:
    types: [new-repo-created]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create Issue
      uses: actions/github-script@v5
      with:
        script: |
          const issueTitle = 'Welcome to your new repository!';
          const issueBody = 'Thank you for using this template. Here are some steps to get started...';
          const response = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody
          });
          core.setOutput('issue', response.data.html_url);
